/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aiController_ScreenCapture */

#ifndef _Included_aiController_ScreenCapture
#define _Included_aiController_ScreenCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aiController_ScreenCapture
 * Method:    captureScreen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_aiController_ScreenCapture_captureScreen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
